sudo: false

language: php

install:
  - composer validate
  - composer install

matrix:
  fast_finish: true

jobs:
  include:
    - stage: lint
      php: 7.1
      install:
        - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
        - composer require "phpstan/phpstan" "friendsofphp/php-cs-fixer:^2.8"
        # dependencies for phpstan
        - composer require --dev "symfony/symfony" "laravel/framework"
      script:
        # Unit test
        - ./vendor/bin/phpunit
        # Static analyzer check
        - ./vendor/bin/phpstan analyze -c .phpstan.neon --level=4 --no-progress Bootstraps Bridges Laravel
        # Check the code style
        - IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS
        - ./vendor/bin/php-cs-fixer fix --config=.php_cs.php -v --dry-run --diff --stop-on-violation --using-cache=no --path-mode=intersection -- "${COMMIT_SCA_FILES[@]}"

# Cache package sources
cache:
  directories:
    - $HOME/.composer/cache
